services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "S3cur3P@ss2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build:
      dockerfile: Dockerfile
    image: proyecto-backend
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=Bookme;User=sa;Password=S3cur3P@ss2024!;TrustServerCertificate=True
    ports:
      - "5000:80"
    volumes:
      - backendvolume:/app/uploads

volumes:
  sqlvolume:
  backendvolume:
